### ISSUE TITLE
Homekit set temperature dial in Fahrenheit range 

### ISSUE THREAD

**Issue by MrGreiss** [bgottsch/homebridge-sensibo-hub#1]
Hey,

## Description:
So I've tried setting everything up. And everything should be in Celsius. The reported temps are in C in Homekit and in Sensibo correctly. But the dial which you set up the range for cooling or heating is in F but acting as C so when you try to set it through API you get an error that you are setting a temp out of range 

## Repro steps:

1. Make sure Sensibo is off
2. Set Sensibo to Celsius
3. Go to home app 
4. See that the reported temperature is in Celsius
5. Try turning on cooling 
6. See that the set cooling is for instance 63 degrees 
7. Go into Homebridge see an error from Sensibo API

## Log form homebridge
` message: "Invalid targetTemperature in AcState(on=True, mode=cool, temp=71F, fan=medium, swing=rangeFull) (capabilities: RemoteCapabilities: {'modes': {'dry': {'swing': ['stopped', 'rangeFull'], 'temperatures': {'celsius': [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]}, 'fanLevels': ['low']}, 'auto': {'swing': ['stopped', 'rangeFull'], 'temperatures': {'celsius': [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]}, 'fanLevels': ['low', 'medium_low', 'medium', 'medium_high', 'high', 'auto', 'strong']}, 'heat': {'swing': ['stopped', 'rangeFull'], 'temperatures': {'celsius': [8, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]}, 'fanLevels': ['low', 'medium_low', 'medium', 'medium_high', 'high', 'auto', 'strong']}, 'fan': {'swing': ['stopped', 'rangeFull'], 'fanLevels': ['low', 'medium_low', 'medium', 'medium_high', 'high', 'auto', 'strong']}, 'cool': {'swing': ['stopped', 'rangeFull'], 'temperatures': {'celsius': [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]}, 'fanLevels': ['low', 'medium_low', 'medium', 'medium_high', 'high', 'auto', 'strong']}}})",
      result: [Object]
    },`

**Comment by bgottsch** [comment]
Hi,

I'm aware of this error, and a few other as well. I made a mistake in releasing it in it's current state, since more work need to be done.

I'll try to finish it by the end of the week, it should take long.

Sorry for the inconvenience. While at it, if you have any suggestions on ways to improve this plugin, I'll be happy to listen to them.

Best regards

**Comment by MrGreiss** [comment]
Heh, thank no worries I am just glad that I found something recent and actively worked on as all the other plugins are a bit old (They maybe work though).

I don't have much experience with other plugins for Homebridge but would there be a way to have just a fan option? Like currently it's Automatic, Heat, Cool and maybe fan option? (Maybe there is a way already but just couldn't figure it out)

**Comment by bgottsch** [comment]
No worries, great way to spend my time these days...

Yes, it is possible. The big issue here is to convert Sensibo characteristics and states to HomeKit characteristics and states.

Currently, HK (HomeKit) supports a HeaterCooler service, which is most closly related to an A/C. Therefore there are some hickups: auto mode has logical issues, and other modes such as fan cannot be supported (it has limited modes).

HK also has support for fans, but this would split the accessory into 2 (HeaterCooler and Fan), which complicates life in the Home app.

I'm trying to find a solution to this problem, and a few other. Started working on a new version now, and will probably have something new by the end of the week.

Possibly, there might be a way to implement a both services (HeaterCooler and Fan) in a neat manner. I'll let you know if I have any further progress.

Best regards

**Comment by bgottsch** [comment]
@Greisss 

Hey, just uploaded a new version. I still have to test,but it's stable at the moment.

I also was able to include functionality for fan/dry modes, take a look at the README

Best regards
