### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by seaner1024** [bgottsch/homebridge-sensibo-hub#2]
Hi, thanks for taking the time to create this plugin.

I am receiving an error in the log indicating "TypeError: Cannot read property 'length' of undefined"

If you can shed any light on this. Much appreciated.

**Comment by bgottsch** [comment]
Hi @seaner1024 

Thanks for using it. Currently, as described in issue [#1](https://github.com/bgottsch/homebridge-sensibo-hub/issues/1), there are some issues with the version I released.

I'll try to get a stable version by the end of the week. I'll keep you posted on updates.

Let me know if you have any further questions/suggestions on thsi plugin.

Best regards

**Comment by bgottsch** [comment]
@seaner1024 

Hey, just uploaded a new version. I still have to test, but it's stable in it's current state.

Best regards

**Comment by seaner1024** [comment]
Awesome! Thanks for the effort. Will let you know if I run into something.
