### ISSUE TITLE
No data coming to the home app

### ISSUE THREAD

**Issue by MrGreiss** [bgottsch/homebridge-sensibo-hub#3]
Hey, 

I've tried debugging in the homebridge but without luck. So the problem is that temp in the home app is 0.0 and when you try to set anything it seems on but with "Set to (null)" and I cannot see anything happening in the homebridge app.

Homebridge version: 0.4.53
Sensibo-hub version: v0.5.4
iOS version: 13.4

![IMG_1066](https://user-images.githubusercontent.com/15111964/79688379-44b51700-824e-11ea-9a27-847e908cf823.PNG)

**Comment by bgottsch** [comment]
Hey @Greisss,

Thanks for using it an testing.

This might be related to a wrong translation on the plugin's side, when getting the current state. If possible, can you share a snipped from your Sensibo API (only the remoteCapabilites part)?

Steps to share:
1- use a program such as Postman
2- send a `GET` request to `https://home.sensibo.com/api/v2/users/me/pods?fields=remoteCapabilities&apiKey=YOUR_API_KEY`
3- If successful, some JSON should be the result
4- Just copy and paste it. Please double check if no sensitive info is exposed before sharing, there should be none

As I have little info on your setup, so it's hard to know exactly whats wrong. As there are no problems with the configuarion/addition/removal of devices, the most probabal error is incorrect an readout of Sensibo info from API, about the remote capabilities.

Best regards

**Comment by MrGreiss** [comment]
`{
    "status": "success",
    "result": [
        {
            "remoteCapabilities": {
                "modes": {
                    "dry": {
                        "swing": [
                            "stopped",
                            "rangeFull"
                        ],
                        "temperatures": {
                            "C": {
                                "isNative": true,
                                "values": [
                                    17,
                                    18,
                                    19,
                                    20,
                                    21,
                                    22,
                                    23,
                                    24,
                                    25,
                                    26,
                                    27,
                                    28,
                                    29,
                                    30
                                ]
                            },
                            "F": {
                                "isNative": false,
                                "values": [
                                    63,
                                    64,
                                    66,
                                    68,
                                    70,
                                    72,
                                    73,
                                    75,
                                    77,
                                    79,
                                    81,
                                    82,
                                    84,
                                    86
                                ]
                            }
                        },
                        "fanLevels": [
                            "low"
                        ]
                    },
                    "auto": {
                        "swing": [
                            "stopped",
                            "rangeFull"
                        ],
                        "temperatures": {
                            "C": {
                                "isNative": true,
                                "values": [
                                    17,
                                    18,
                                    19,
                                    20,
                                    21,
                                    22,
                                    23,
                                    24,
                                    25,
                                    26,
                                    27,
                                    28,
                                    29,
                                    30
                                ]
                            },
                            "F": {
                                "isNative": false,
                                "values": [
                                    63,
                                    64,
                                    66,
                                    68,
                                    70,
                                    72,
                                    73,
                                    75,
                                    77,
                                    79,
                                    81,
                                    82,
                                    84,
                                    86
                                ]
                            }
                        },
                        "fanLevels": [
                            "low",
                            "medium_low",
                            "medium",
                            "medium_high",
                            "high",
                            "auto",
                            "strong"
                        ]
                    },
                    "heat": {
                        "swing": [
                            "stopped",
                            "rangeFull"
                        ],
                        "temperatures": {
                            "C": {
                                "isNative": true,
                                "values": [
                                    8,
                                    17,
                                    18,
                                    19,
                                    20,
                                    21,
                                    22,
                                    23,
                                    24,
                                    25,
                                    26,
                                    27,
                                    28,
                                    29,
                                    30
                                ]
                            },
                            "F": {
                                "isNative": false,
                                "values": [
                                    46,
                                    63,
                                    64,
                                    66,
                                    68,
                                    70,
                                    72,
                                    73,
                                    75,
                                    77,
                                    79,
                                    81,
                                    82,
                                    84,
                                    86
                                ]
                            }
                        },
                        "fanLevels": [
                            "low",
                            "medium_low",
                            "medium",
                            "medium_high",
                            "high",
                            "auto",
                            "strong"
                        ]
                    },
                    "fan": {
                        "swing": [
                            "stopped",
                            "rangeFull"
                        ],
                        "temperatures": {},
                        "fanLevels": [
                            "low",
                            "medium_low",
                            "medium",
                            "medium_high",
                            "high",
                            "auto",
                            "strong"
                        ]
                    },
                    "cool": {
                        "swing": [
                            "stopped",
                            "rangeFull"
                        ],
                        "temperatures": {
                            "C": {
                                "isNative": true,
                                "values": [
                                    17,
                                    18,
                                    19,
                                    20,
                                    21,
                                    22,
                                    23,
                                    24,
                                    25,
                                    26,
                                    27,
                                    28,
                                    29,
                                    30
                                ]
                            },
                            "F": {
                                "isNative": false,
                                "values": [
                                    63,
                                    64,
                                    66,
                                    68,
                                    70,
                                    72,
                                    73,
                                    75,
                                    77,
                                    79,
                                    81,
                                    82,
                                    84,
                                    86
                                ]
                            }
                        },
                        "fanLevels": [
                            "low",
                            "medium_low",
                            "medium",
                            "medium_high",
                            "high",
                            "auto",
                            "strong"
                        ]
                    }
                }
            }
        }
    ]
}`

**Comment by bgottsch** [comment]
Thanks for the info!

Still testing with your setup, but couldn't reproduce error yet.

A wild guess, did you try to reset your cached accessories (removed the ./homebridge/accessories directory)? This might be a possible cause to the issue.

**Comment by MrGreiss** [comment]
It did help to reset the cache thank you
